### ISSUE TITLE
no magic numbers -> starting coins should be a constant

### ISSUE THREAD

**Issue by incredibleLeitman** [chikanildi/slotmachine#1]
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L7

**Comment by chikanildi** [comment]
the "Coins" variable change. In line 85 for example: the betAmount is added to it.

**Comment by incredibleLeitman** [comment]
Yes, your "coins" variable should stay at it is, but instead of just assigning it a plain value you should use a constant like
```
const int STARTING_COINS = 1000;
...
int coins = STARTING_COINS;
```
