### ISSUE TITLE
Is this check really necessary?

### ISSUE THREAD

**Issue by incredibleLeitman** [chikanildi/slotmachine#2]
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L30

a few lines before you check if the given input is within the valid range, otherwise you continue the loop iteration
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L25
so at this point you value should definitively be valid. 

Also, those values could be constants and be referenced in your user output instead of having it hardcoded:
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L19
Using the same variable will help you preventing errors when modifying your code. For example, if you now would want to change the minimum bet to lets say 10 instead of 1 you have to change it at three different locations, which is very error prone and easy that you forget one place. Having only one variable would completely eliminate this potential pitfall :D

**Comment by chikanildi** [comment]
Created a slotmachine2 repository and maybe it will find the files now. I changed 1 and 100 to min and maxBet constants.

**Comment by incredibleLeitman** [comment]
Haha nooo, you should not create a new repository for fixing issues, this makes it really hard to keep track of the changes 🙈 

If you have trouble working on this project you could just "clone" it from github to your local machine and continue working from there :D

**Comment by incredibleLeitman** [comment]
in your project page on github you have a "Code" button where you can make the connection from this repository to the code on your maching
![image](https://user-images.githubusercontent.com/24638443/223284333-7781065f-49a2-4d25-b7c3-7aea76dff6e8.png)
https://github.com/chikanildi/slotmachine
