### ISSUE TITLE
Hardcoded "3" looks like a magic number

### ISSUE THREAD

**Issue by incredibleLeitman** [chikanildi/slotmachine#3]
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L32-L34

While those are in fact the dimensions of your grid 👆 
To make this better visible (and also easier to maintain) you should also get it from the grid :D

"GetLength(dimension)" is the function you should look at for this:
https://learn.microsoft.com/en-us/dotnet/api/system.array.getlength?redirectedfrom=MSDN&view=net-7.0#System_Array_GetLength_System_Int32_

Also using "row" and "col" for example as loop variables would make your code much more readable than just i and j

**Comment by chikanildi** [comment]
changed the 3s to:
int numRows = spin.GetLength(0);
 int numCols = spin.GetLength(1);
