### ISSUE TITLE
Deduct bet also for winnings

### ISSUE THREAD

**Issue by incredibleLeitman** [chikanildi/slotmachine#4]
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L83
You currently only reducing the bet amount when the player has lost -> which means in case of winning the play was free AND grants a bonus. I think it would be more consistent to game logic if you deduct the bet regardless of the win condition but just directly if the player plays another round

**Comment by chikanildi** [comment]
I am not sure I understand. Let's say the user bets 70 coins, spins then wins 70 coins. The coins become 1070. Once he spins again he should lose the 70? Would not he end up with always max 1000 coins?

**Comment by chikanildi** [comment]
I am not sure I understand. Can you please explain a possible scenario with the variables?
for example: 
betAmount: 50,  win, 1 matching row, coins =1050
playAgain: yes
betAmount: 20,  win, 3 matching rows,  coins = ?
playAgain: yes
betAmount: 30, win, 1 matching row, coins.=?

Thank you!

**Comment by incredibleLeitman** [comment]
Usually in slotmachines, you win a multiple of your bet if you manage to get one matching row.
So in your example, the final output for the user may look like the same result:
Start with 1000 credits - bet 50 - and after a win has 1050, 
when not winning 950.

But the order here is important: you directly calculate the final credits after determine if it is a win or not,
where in fact this should be two steps:
first, the user want to play one round -> so the bet should be deducted and the user only has 950 credits (when starting with 1000)
After that you check if it is a win: if yes, you can add the bet multiplied by an win-factor. I you would for example use a multiplier of 2, the user would win 2*50 credits = 100 so finally having 1050 credits.
If it was not a win, there are no credits granted to the user at this point.

It is important to understand that this are two separate steps 👆 
As mentioned, for the user the result shown is exactlty the same, but this becomes very important when working on client - server applications.
