### ISSUE TITLE
Declare "matches" inside your check-logic

### ISSUE THREAD

**Issue by incredibleLeitman** [chikanildi/slotmachine#5]
You currently have defined your variable to keep track of the matching lines on top of your loop
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L13
and reset it if the player wants to play again
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L97

It is usually easier to follow your code if you keep variables just where they are needed and grouped together 👆 
Also, if you just declare your "matches" variable inside your loop, it will automatically start at 0 for every round and you don't need to reset it manually.

**Comment by chikanildi** [comment]
moved it inside the loop
