### ISSUE TITLE
duplicated code here

### ISSUE THREAD

**Issue by incredibleLeitman** [chikanildi/slotmachine#7]
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L78
https://github.com/chikanildi/slotmachine/blob/cb8b30ec27bf4dad3198fcf3a29425e71329c4ba/slotmachine/Program.cs#L89

you print the exact same output regardless of winning or not, so this could just moved below those conditions

**Comment by chikanildi** [comment]
moved it outside the conditions

**Comment by chikanildi** [comment]
moved it outside the conditions
